export const DEFAULT_AUTOMOD_CONFIG = {
  enabled: false,
  deleteMessage: true,
  warnOnFilter: false,
  timeoutOnRepeat: false,
  timeoutMinutes: 10,
  strikeLimit: 3,
  strikeWindowMs: 10 * 60 * 1000,
  exemptRoles: [],
  exemptChannels: [],
  ignoredWords: [],
  customWords: [],
  customPhrases: [],
  filters: {
    words: true,
    phrases: true,
    invites: true,
    links: false,
    massMentions: true,
    massMentionLimit: 5,
    caps: false,
    capsPercent: 75,
    capsMinLength: 16,
    spam: true,
    spamCount: 5,
    spamWindowMs: 8000,
    zalgo: true,
  },
};

export const AUTOMOD_FILTER_CHOICES = [
  { name: 'Blocked words', value: 'words' },
  { name: 'Blocked phrases', value: 'phrases' },
  { name: 'Discord invites', value: 'invites' },
  { name: 'External links', value: 'links' },
  { name: 'Mass mentions', value: 'massMentions' },
  { name: 'Excessive caps', value: 'caps' },
  { name: 'Repeated spam', value: 'spam' },
  { name: 'Zalgo / glitch text', value: 'zalgo' },
];
